# Challenge 1 - T-test

In statistics, t-test is used to test if two data samples have a significant difference between their means. There are two types of t-test:

* **Student's t-test** (a.k.a. independent or uncorrelated t-test). This type of t-test is to compare the samples of **two independent populations** (e.g. test scores of students in two different classes). `scipy` provides the [`ttest_ind`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_ind.html) method to conduct student's t-test.

* **Paired t-test** (a.k.a. dependent or correlated t-test). This type of t-test is to compare the samples of **the same population** (e.g. scores of different tests of students in the same class). `scipy` provides the [`ttest_re`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_rel.html) method to conduct paired t-test.

Both types of t-tests return a number which is called the **p-value**. If p-value is below 0.05, we can confidently declare the null-hypothesis is rejected and the difference is significant. If p-value is between 0.05 and 0.1, we may also declare the null-hypothesis is rejected but we are not highly confident. If p-value is above 0.1 we do not reject the null-hypothesis.

Read more about the t-test in [this article](https://researchbasics.education.uconn.edu/t-test/) and [this Quora](https://www.quora.com/What-is-the-difference-between-a-paired-and-unpaired-t-test). Make sure you understand when to use which type of t-test.

In [13]:
# Import libraries

import pandas as pd
import scipy.stats as st

#### Import dataset

In this challenge we will work on the Pokemon dataset you have used last week. The goal is to test whether different groups of pokemon (e.g. Legendary vs Normal, Generation 1 vs 2, single-type vs dual-type) have different stats (e.g. HP, Attack, Defense, etc.).

In [2]:
# Import dataset

pokemon = pd.read_csv('C:/Users/anmnu/DSML/Week4/Day18/Lab/lab-hypothesis-testing-en/data/Pokemon.csv')

pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

#### First we want to define a function with which we can test the means of a feature set of two samples. 

In the next cell you'll see the annotations of the Python function that explains what this function does and its arguments and returned value. This type of annotation is called **docstring** which is a convention used among Python developers. The docstring convention allows developers to write consistent tech documentations for their codes so that others can read. It also allows some websites to automatically parse the docstrings and display user-friendly documentations.

Follow the specifications of the docstring and complete the function.

In [15]:
def t_test_features(s1, s2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']):
    """Test means of a feature set of two samples
    
    Args:
        s1 (dataframe): sample 1
        s2 (dataframe): sample 2
        features (list): an array of features to test
    
    Returns:
        dict: a dictionary of t-test scores for each feature where the feature name is the key and the p-value is the value
    """
    results = {}

    # Your code here
    df1 = s1[features]
    df2 = s2[features]

    for feature in features:
        stat, pval = st.ttest_ind(df1[feature], df2[feature])
        results[feature] = (stat, pval)
    
    return results

#### Using the `t_test_features` function, conduct t-test for Lengendary vs non-Legendary pokemons.

*Hint: your output should look like below:*

```
{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}
 ```

In [4]:
# we have to create legendary and non-legendary
pokemon["Legendary"].value_counts()

Legendary
False    735
True      65
Name: count, dtype: int64

In [9]:
legendary = pokemon[pokemon["Legendary"] == True]

non_legendary = pokemon[pokemon["Legendary"] == False]

In [10]:
legendary

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
156,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [11]:
non_legendary

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,711,GourgeistSuper Size,Ghost,Grass,494,85,100,122,58,75,54,6,False
788,712,Bergmite,Ice,NaN,304,55,69,85,32,35,28,6,False
789,713,Avalugg,Ice,NaN,514,95,117,184,44,46,28,6,False
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False

In [16]:
# Your code here
t_test_features(legendary, non_legendary, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total'])

{'HP': (np.float64(8.036124405043928), np.float64(3.3306476848461905e-15)),
 'Attack': (np.float64(10.397321023700622), np.float64(7.827253003205253e-24)),
 'Defense': (np.float64(7.181240122992339),
  np.float64(1.5842226094427243e-12)),
 'Sp. Atk': (np.float64(14.191406210846289),
  np.float64(6.314915770427278e-41)),
 'Sp. Def': (np.float64(11.03775106120522), np.float64(1.843980958040965e-26)),
 'Speed': (np.float64(9.765234331931898), np.float64(2.3540754436898388e-21)),
 'Total': (np.float64(16.386116965872425), np.float64(3.0952457469651812e-52))}

#### From the test results above, what conclusion can you make? Do Legendary and non-Legendary pokemons have significantly different stats on each feature?

In [ ]:
# Your comment here
# For all the features, they seem to all have a pvalue smaller than 0.05, telling us that all features of 
# legendary are significantly different from non-legendary

#### Next, conduct t-test for Generation 1 and Generation 2 pokemons.

In [17]:
pokemon["Generation"].value_counts()

Generation
1    166
5    165
3    160
4    121
2    106
6     82
Name: count, dtype: int64

In [25]:
pokemon["Generation"].unique()

array([1, 2, 3, 4, 5, 6])

In [26]:
# Your code here
gen1 = pokemon[pokemon["Generation"] == 1]
gen2 = pokemon[pokemon["Generation"] == 2]

In [30]:
gen1

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,149,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
165,151,Mew,Psychic,NaN,600,100,100,100,100,100,100,1,False

In [29]:
gen2

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
166,152,Chikorita,Grass,NaN,318,45,49,65,49,65,45,2,False
167,153,Bayleef,Grass,NaN,405,60,62,80,63,80,60,2,False
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,248,Tyranitar,Rock,Dark,600,100,134,110,95,100,61,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
269,249,Lugia,Psychic,Flying,680,106,90,130,90,154,110,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
271,251,Celebi,Psychic,Grass,600,100,100,100,100,100,100,2,False

In [31]:
t_test_features(gen1, gen2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total'])

{'HP': (np.float64(-1.4879963792658193), np.float64(0.1379188141281361)),
 'Attack': (np.float64(1.1763035045816723), np.float64(0.24050968418101443)),
 'Defense': (np.float64(-0.6124386271679768), np.float64(0.5407630349194361)),
 'Sp. Atk': (np.float64(1.475669371406143), np.float64(0.14119788176331505)),
 'Sp. Def': (np.float64(-1.3829844029533516), np.float64(0.16781226231606378)),
 'Speed': (np.float64(3.0126333688329856), np.float64(0.0028356954812578674)),
 'Total': (np.float64(0.5836931395106778), np.float64(0.5599140649014442))}

#### What conclusions can you make?

In [ ]:
# Your comment here
# Here we can see that only speed (the pvalue) is smaller than 0.05. Only for speed we can reject the 
# null and say that it is significantly different. Cannot make the same conclusion for other features.

#### Compare pokemons who have single type vs those having two types.

In [43]:
pokemon["Type 1"].isna().sum()

np.int64(0)

In [42]:
pokemon["Type 2"].isna().sum()

np.int64(386)

In [45]:
# Your code here
# df for two types: Type 2 does nto have NaN
# df for one type: Type 2 IS NaN

one_type = pokemon[pokemon["Type 2"].isna()]
two_types = pokemon[pokemon["Type 2"].notna()]

In [46]:
one_type

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,705,Sliggoo,Dragon,NaN,452,68,75,53,83,113,60,6,False
776,706,Goodra,Dragon,NaN,600,90,100,70,110,150,80,6,False
788,712,Bergmite,Ice,NaN,304,55,69,85,32,35,28,6,False
789,713,Avalugg,Ice,NaN,514,95,117,184,44,46,28,6,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True

In [47]:
two_types

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [48]:
t_test_features(one_type, two_types, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total'])

{'HP': (np.float64(-1.597247491548339), np.float64(0.11060643144431839)),
 'Attack': (np.float64(-3.7972414565658683),
  np.float64(0.00015741395666164405)),
 'Defense': (np.float64(-5.58247971732322), np.float64(3.250594205756991e-08)),
 'Sp. Atk': (np.float64(-3.8170824160380157),
  np.float64(0.0001454917404035149)),
 'Sp. Def': (np.float64(-3.8892352214769463),
  np.float64(0.00010893304795534405)),
 'Speed': (np.float64(-2.2606203667533133), np.float64(0.024051410794037456)),
 'Total': (np.float64(-5.345970873144627), np.float64(1.1749035008828765e-07))}

#### What conclusions can you make?

In [ ]:
# Your comment here
# Features that are significantly different are Attack, Defense, Sp. Atk, Sp. Def, Speed, and Total

#### Now, we want to compare whether there are significant differences of `Attack` vs `Defense`  and  `Sp. Atk` vs `Sp. Def` of all pokemons. Please write your code below.

*Hint: are you comparing different populations or the same population?*

In [ ]:
# Your code here
# We are comparing the same population, so dependent, and we will use ttest_rel

In [49]:
# attack vs defense
st.ttest_rel(pokemon["Attack"], pokemon["Defense"])

TtestResult(statistic=np.float64(4.325566393330478), pvalue=np.float64(1.7140303479358582e-05), df=np.int64(799))

In [50]:
# sp atk vs sp def
st.ttest_rel(pokemon["Sp. Atk"], pokemon["Sp. Def"])

TtestResult(statistic=np.float64(0.853986188453353), pvalue=np.float64(0.3933685997548118), df=np.int64(799))

#### What conclusions can you make?

In [ ]:
# Your comment here

* For Attack vs Defense, the pvalues show that there is a significance difference among the same population
* For Sp. Atk vs Sp. Def, pvalue shows that we cannot reject the null hypothesis and cannot make comments on whether there is a significant difference