# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas
import pandas as pd
import numpy as np
from scipy.stats import trim_mean, mode, skew, gaussian_kde, pearsonr, spearmanr, beta
from statsmodels.stats.weightstats import ztest as ztest

from scipy.stats import ttest_ind, norm, t
from scipy.stats import f_oneway
from scipy.stats import sem

# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents

In [8]:
# Run this code:
salaries = pd.read_csv('../data\Current_Employee_Names__Salaries__and_Position_Titles.csv')

Examine the `salaries` dataset using the `head` function below.

In [13]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33183 entries, 0 to 33182
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               33183 non-null  object
 1   Job Titles         33183 non-null  object
 2   Department         33183 non-null  object
 3   Full or Part-Time  33183 non-null  object
 4   Salary or Hourly   33183 non-null  object
 5   Typical Hours      8022 non-null   float64
 6   Annual Salary      25161 non-null  float64
 7   Hourly Rate        8022 non-null   float64
dtypes: float64(3), object(5)
memory usage: 2.0+ MB

Table Insights
1. The typical Hours have 25161 missing numbers which suggests that 25161 employees are salaried employees who receive their salaries monthly and not based on hours.
2. The table has 25161 salaried employees. The Annual salary column suggests this as it is missing 8022 numbers.
3. The hourly rate column also has only 8022 data values thereby missing 25161 values (that of annual salaried employees)

In [9]:
salaries.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,101442.0,NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,101592.0,NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,110064.0,NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [28]:
import scipy.stats as st

In [29]:
hourly_emp = salaries[salaries['Salary or Hourly'] == 'Hourly']
hourly_emp

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86
6,"ABBATACOLA, ROBERT J",ELECTRICAL MECHANIC,AVIATION,F,Hourly,40.0,NaN,46.10
7,"ABBATE, JOSEPH L",POOL MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40.0,NaN,35.60
10,"ABBOTT, BETTY L",FOSTER GRANDPARENT,FAMILY & SUPPORT,P,Hourly,20.0,NaN,2.65
18,"ABDULLAH, LAKENYA N",CROSSING GUARD,OEMC,P,Hourly,20.0,NaN,17.68
...,...,...,...,...,...,...,...,...
33164,"ZUREK, FRANCIS",ELECTRICAL MECHANIC,OEMC,F,Hourly,40.0,NaN,46.10
33168,"ZWARYCZ MANN, IRENE A",CROSSING GUARD,OEMC,P,Hourly,20.0,NaN,17.68
33169,"ZWARYCZ, THOMAS J",POOL MOTOR TRUCK DRIVER,WATER MGMNT,F,Hourly,40.0,NaN,35.60
33174,"ZYGADLO, JOHN P",MACHINIST (AUTOMOTIVE),GENERAL SERVICES,F,Hourly,40.0,NaN,46.35
33175,"ZYGADLO, MICHAEL J",FRM OF MACHINISTS - AUTOMOTIVE,GENERAL SERVICES,F,Hourly,40.0,NaN,48.85

In [30]:
hourly_rate = hourly_emp['Hourly Rate']

In [31]:
# H0: u = 30; H1: u != 30;
result = st.ttest_1samp(hourly_rate, 30)
result

TtestResult(statistic=np.float64(20.6198057854942), pvalue=np.float64(4.323024048623005e-92), df=np.int64(8021))

The null hypothesis H0 is rejected because pvalue <0.05. The hourly average wage is not 30.

In [ ]:
# H0: u<= 30; H1: u>30;
result1 = st.ttest_1samp(hourly_rate, 30, alternative='greater')
result1

TtestResult(statistic=np.float64(20.6198057854942), pvalue=np.float64(2.1615120243115026e-92), df=np.int64(8021))

pvalue < 0.05, H0 is rejected and the hourly average salary is not smaller than 30.

In [ ]:
# H0: u> 30
result2 = st.ttest_1samp(hourly_rate, 30, alternative='less')
result2

TtestResult(statistic=np.float64(20.6198057854942), pvalue=np.float64(1.0), df=np.int64(8021))

In [46]:
avg = hourly_rate.mean()
avg

np.float64(32.78855771628024)

# Challenge 3 - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [41]:
hourly_rate.describe()

count    8022.000000
mean       32.788558
std        12.112573
min         2.650000
25%        21.200000
50%        35.600000
75%        40.200000
max       109.000000
Name: Hourly Rate, dtype: float64

In [52]:
standard_error = st.sem(hourly_rate)
standard_error

np.float64(0.1352368565101596)

In [53]:
CI = st.t.interval(0.95, df=len(hourly_rate)-1, loc=avg, scale=standard_error)
CI

(np.float64(32.52345834488425), np.float64(33.05365708767623))

# Challenge 4 - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [ ]:

from statsmodels.stats.proportion import proportions_ztest

In [57]:
salaries.head(20)

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,101442.0,NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,101592.0,NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,110064.0,NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86
5,"ABBASI, CHRISTOPHER",STAFF ASST TO THE ALDERMAN,CITY COUNCIL,F,Salary,NaN,50436.0,NaN
6,"ABBATACOLA, ROBERT J",ELECTRICAL MECHANIC,AVIATION,F,Hourly,40.0,NaN,46.10
7,"ABBATE, JOSEPH L",POOL MOTOR TRUCK DRIVER,STREETS & SAN,F,Hourly,40.0,NaN,35.60
8,"ABBATEMARCO, JAMES J",FIRE ENGINEER-EMT,FIRE,F,Salary,NaN,103350.0,NaN
9,"ABBATE, TERRY M",POLICE OFFICER,POLICE,F,Salary,NaN,93354.0,NaN
10,"ABBOTT, BETTY L",FOSTER GRANDPARENT,FAMILY & SUPPORT,P,Hourly,20.0,NaN,2.65
11,"ABDALLAH, ZAID",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
12,"ABDELHADI, ABDALMAHD",POLICE OFFICER,POLICE,F,Salary,NaN,87006.0,NaN
13,"ABDELLATIF, AREF R",FIREFIGHTER (PER ARBITRATORS AWARD)-PARAMEDIC,FIRE,F,Salary,NaN,102228.0,NaN
14,"ABDELMAJEID, AZIZ",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
15,"ABDOLLAHZADEH, ALI",FIREFIGHTER/PARAMEDIC,FIRE,F,Salary,NaN,91272.0,NaN
16,"ABDUL-KARIM, MUHAMMAD A",ENGINEERING TECHNICIAN VI,WATER MGMNT,F,Salary,NaN,111492.0,NaN
17,"ABDULLAH, DANIEL N",FIREFIGHTER-EMT,FIRE,F,Salary,NaN,95484.0,NaN
18,"ABDULLAH, LAKENYA N",CROSSING GUARD,OEMC,P,Hourly,20.0,NaN,17.68
19,"ABDULLAH, RASHAD",ELECTRICAL MECHANIC (AUTOMOTIVE),GENERAL SERVICES,F,Hourly,40.0,NaN,46.10

In [59]:
total_emp = len(salaries)
total_emp

33183

In [60]:
total_hourly= len(hourly_emp)
total_hourly

8022

In [ ]:
# H0: u =0.25, H1: u !=0.25
p = 0.25
result = proportions_ztest(count=total_hourly, nobs=total_emp, value=p)
result

(np.float64(-3.5099964213703005), np.float64(0.0004481127249057967))

Pvalue < 0.05, we reject H0. The proportion of hourly worker is not 25%

In [67]:
# H0: u <=0.25, H1: u >0.25
p = 0.25
result1 = proportions_ztest(count=total_hourly, nobs=total_emp, value=p, alternative='larger')
result1

(np.float64(-3.5099964213703005), np.float64(0.9997759436375471))

The pvalue is larger than 0.05. we fail to reject H0.